### ISSUE TITLE
React Native beyond mobile?

### ISSUE THREAD

**Issue by garyrob** [martinmoec/fable-react-native-how-to#4]
Hello,
The How-Toi for Fable React Native say that it "lets you write React Native apps targeting iOS and Android almost completely through F#". But lately React Native can also target Windows, MacOS and web.

I'm wondering if there are substantial barriers to using Fable React Native in those other contexts. If not, maybe it would be appropriate to update the How-To accordingly?

**Comment by martinmoec** [comment]
Hi!

Personally i have only tested building against iOS and Android. Since the Fable compiler is just generating pure JavaScript from our F# code, we should be able to target the same platforms through F# as through JavaScript. Any JavaScript functionality missing from F# (Fable/Fable.ReactNative) you can write bindings for, enabling you to access these functions through F#. See any of my other Fable.ReactNative.* projects for bindings samples.

I will update the how-to to include this.

**Comment by garyrob** [comment]
Makes perfect sense. Thanks!
